arch:
  - arm64
os: linux

language: generic

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - chmod +x run.sh
  - travis_retry docker -v /src:/ run moussavdb/build-graalvm-arm64 ls
