arch:
  - arm64
os: linux

language: generic

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - travis_retry docker run moussavdb/build-graalvm-arm64 java -version
