arch:
  - arm64
os: linux

language: generic

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - travis_retry docker -v /src:/ run moussavdb/build-graalvm-arm64 /bin/bash -c "javac be/yildizgames/test/arm/*.java; ls -l"
