arch:
  - arm64
os: linux

language: generic

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - chmod +x src/run.sh
  - travis_retry docker run -w /src -v ${pwd}/src:/src moussavdb/build-graalvm-arm64 /bin/bash ./run.sh
